language: php
sudo: false
cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/symfony-bridge/.phpunit

env:
  global:
    - PHPUNIT_FLAGS="-v"
    - SYMFONY_PHPUNIT_DIR="$HOME/symfony-bridge/.phpunit"
    - SYMFONY_DEPRECATIONS_HELPER="999999"

matrix:
  fast_finish: true
  include:
    - php: 8.0

before_install:
  - phpenv config-rm xdebug.ini || true
  - phpenv global 8.0; phpenv global $TRAVIS_PHP_VERSION

install:
  - composer update $COMPOSER_FLAGS --no-interaction
  - phpenv global 8.0; ./vendor/bin/simple-phpunit install; phpenv global $TRAVIS_PHP_VERSION

script:
  - composer validate --strict --no-check-lock
  - ./vendor/bin/simple-phpunit $PHPUNIT_FLAGS